# Generated by Django 3.0.8 on 2020-07-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='D:\\workspace\\tms\\root\\media'),
        ),
    ]
