# Generated by Django 3.0.8 on 2020-07-24 18:58

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[shop.models.validate_name])),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=100)),
            ],
        ),
    ]
